/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {AppResponse} from '../../models/app-response';

export interface DeleteCourse$Params {
  id: number;
}

export function deleteCourse(http: HttpClient, rootUrl: string, params: DeleteCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<AppResponse>> {
  const rb = new RequestBuilder(rootUrl, deleteCourse.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppResponse>;
    })
  );
}

deleteCourse.PATH = '/api/v1/courses/{id}';
