/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {AppResponse} from '../../models/app-response';
import {RegisterCourse} from '../../models/register-course';

export interface RegisterCourse$Params {
  body: RegisterCourse
}

export function registerCourse(http: HttpClient, rootUrl: string, params: RegisterCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<AppResponse>> {
  const rb = new RequestBuilder(rootUrl, registerCourse.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppResponse>;
    })
  );
}

registerCourse.PATH = '/api/v1/courses/register';
