/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type  {AppResponse} from './models/app-response';
export type {Course} from './models/course';
export type {LoginRequest} from './models/login-request';
export type {LoginResponse} from './models/login-response';
export type {RegisterCourse} from './models/register-course';
export type {User} from './models/user';
export type {UserRegisterRequest} from './models/user-register-request';
export type {UserRegisterResponse} from './models/user-register-response';
