/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {AppResponse} from '../../models/app-response';

export interface ActivateAccount$Params {
  code: string;
  email: string;
}

export function activateAccount(http: HttpClient, rootUrl: string, params: ActivateAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<AppResponse>> {
  const rb = new RequestBuilder(rootUrl, activateAccount.PATH, 'get');
  if (params) {
    rb.query('code', params.code, {});
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppResponse>;
    })
  );
}

activateAccount.PATH = '/api/v1/account/activate';
